language:
- ruby
rvm:
- 2.5.1
cache:
- bundler
services:
- postgresql
before_script:
- psql -c 'create database manugram_test;' -U postgres
before_install:
- sudo apt-get install -y postgresql-server-dev-9.2
script:
- bundle install --jobs=3 --retry=3
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec spec
after_script:
- bundle exec rake coveralls:push
- rake db:migrate
deploy:
  api_key:
    secure: W0wCGh6W5JwwutqqbhDqbHUxXJK6psUfKRNBsy1PReBQ/iriQvsn9vHgclcPXp0NkoinHmxP6BARxxGQS9/X8c0Uv2rrFs6Z14xMcjA80jcdWpXhca+cPfnzycLQeMHDfKA5UHDwdwIMmXZq0YVXDJczndeImlQQBSAqgMAxnG4+1OgpH1eW3GjAks6gBPvpqu4vgVCNsgv5MTR9LpryNJ96iRYgQAIKAJ1HigYkkUCuJdMeAjCkWVv1OgTQGLlwioF8jwlAKpUAWZ6eDow/5Lu3/vwOMCHuNISjM6aLW5G9/97Iiohs8z8Ks2gZaLiMcBNRJ55872kTUz0hKacvrQuYueTjeg8JdnhbQOnMdpgoEJQxovsK0Bjwexgo1pqLANkaXXMY6GqWv8H22JSzrLhQVmmeHa7NAQ4R26k1m1rDGB8vHdAZ6Tmo7Pvs/g9Ura+mcUSgQf64CcMDvYfYVlM11+rcD6cC4Gn8m0BeqlL0JVunuOZru4De5sv1dhJX1gDQT6diW4naaneMhAoPu0iYWvoSDC/Go+7TcVpBaKPWasYOa4TWCyZgGL/GuGmqE+uocD5KtiWrDtOiWUPZXhjTd//XIu/b5yFUB382Lb0Qj/AIUQU0hsgrfLI9lmzCE3hJAxIPGOJuRlaaulnFGMQR0RThT/45LJVbvmpCxh4=
